debug: true
arena-kit-auto-save: false
DEFAULT-THEME: AQUA
disable-save-world: true
lobby-only-commands: []
scoreboard-update-interval: 5
mongo:
  enabled: false
  uri-mode: false
  normal:
    host: localhost
    port: 3306
    auth:
      enabled: false
      username: user
      password: password
  uri:
    database: Practice
    connection-string: mongodb://127.0.0.1:27017/Eden
fancy-tablist:
  enabled: true
  format: '&a{player-name}'
  update-ticks: 20
nametag:
  enabled: true
  prefix:
    lobby: ''
    spectator: '&7'
    teammate: '&a'
    opponent: '&c'
    other: '&7'
party:
  default-max-size: 30
  announce-cooldown: 10
lobby:
  display-players: true
queue:
  ranked-required-wins: 0
match:
  allow-prefire: true
  allow-requeue: true
  outside-cuboid-instant-death: true
  remove-cactus-sugar-cane-physics: true
  death-lightning: true
  death-animation: true
  tp-2-blocks-up-when-die: true
  respawn-teleport-to-spawn-when-die: false
  win-commands: []
  lose-commands: []
  start-saturation: 15
  spectate-expend-cuboid: 50
  golden-apple:
    instant-gapple-effects: true
    give-absorption-hearts-everytime: false
  snow:
    snowball-drop-chance: 50
    snowball-drop-amount: 4
  title:
    score: true
    end: true
  end-duration: 100
  allow-breaking-blocks:
    - DEAD_BUSH
    - GRASS
    - LONG_GRASS
    - CACTUS
  fireball:
    enabled: true
    divide-damage: 5.0
    speed: 2.0
    yield: 2.0
    allowed-breaking-blocks:
      - WOOD
      - ENDER_STONE
    knockback:
      enabled: true
      vertical: 1.1
      horizontal: 1.2
  tnt:
    enabled: true
    divide-damage: 5.0
    yield: 4.0
    fuse-ticks: 50
    allowed-breaking-blocks:
      - WOOD
      - END_STONE
      - ENDER_STONE
    knockback:
      enabled: true
      vertical: 1.1
      horizontal: 1.2
    speed: 2.0
  golden-head:
    effects:
      - REGENERATION;200;2
      - ABSORPTION;2400;0
      - SPEED;200;0
    food-level: 6
event:
  sumo-event:
    arenas:
      - sumoevent
    kit: sumo
chat-format:
  enabled: false
  format: '&a%1$s&f: %2$s'
profile:
  default-elo: 1000
  save-on-server-stop: true
  default-settings:
    time-changer: normal
    arena-selection: false
    match-scoreboard: true
    allow-duel-request: true
    allow-party-invite: true
    spectator-visibility: false
    spectator-join-leave-message: false
    event-announcement: true
    ping-range: infinite
  default:
    theme: AQUA
crafting:
  enabled: false
  whitelisted-items:
    - MUSHROOM_SOUP
imanity:
  teleport-async: true
optimization:
  set-block-fast: true
experiment:
  disable-original-arena: false
  new-arena-chunk-cache: false
  k-factor: 32
