main: rip.diamond.practice.Eden
name: Prax
version: '${version}'
author: GoodestEnglish forked by iRicx
description: The best practice plugin with premium features
depend: [WorldEdit, FastAsyncWorldEdit, ProtocolLib]
softdepend: [ViaVersion, PlaceholderAPI, Citizens]